update:

	wget http://cvs.savannah.gnu.org/viewvc/*checkout*/emacs/emacs/lisp/ido.el
	echo "Get rails-mode from http://rubyforge.org/projects/emacs-rails/"
	wget http://www.emacswiki.org/cgi-bin/emacs/download/java-complete.el
	wget http://www.emacswiki.org/cgi-bin/wiki/download/lorem-ipsum.el
	wget http://perso.tls.cena.fr/boubaker/distrib/mode-compile.el
	echo "Get ri-emacs from http://rubyforge.org/projects/ri-emacs/"
	wget http://www.emacswiki.org/cgi-bin/emacs/download/ruby-block.el
	wget http://www.emacswiki.org/cgi-bin/emacs/download/ruby-compilation.el
	wget http://svn.ruby-lang.org/repos/ruby/trunk/misc/ruby-electric.el
	wget http://svn.ruby-lang.org/repos/ruby/trunk/misc/ruby-mode.el
	wget http://svn.ruby-lang.org/repos/ruby/trunk/misc/ruby-style.el
	wget http://www.kazmier.com/computer/snippet.el
	wget http://www.webweavertech.com/ovidiu/emacs/find-recursive.txt
	mv find-recursive.txt find-recursive.el
	wget http://www.emacswiki.org/cgi-bin/wiki/download/unbound.el
	wget http://github.com/avvo/fuzzy-find-in-project/raw/master/fuzzy-find-in-project.el
	wget http://svn.hamptoncatlin.com/haml/trunk/extra/haml-mode.el