#!/bin/bash

CP=$(echo ~/.emacs.d/clojure/*.jar | tr ' ' ':'):~/.emacs.d/clojure/user.clj

if [ -z "$1" ]; then
  java -cp $CP \
  jline.ConsoleRunner clojure.lang.Repl
else
  java -cp $CP clojure.lang.Script $1
fi
