#!/bin/bash
CLOJURE_DIR=$HOME/.emacs.d/clojure
CLOJURE_JAR=$CLOJURE_DIR/clojure.jar
if [ -z "$1" ]; then
  java -cp $CLOJURE_DIR/jline.jar:$CLOJURE_JAR \
  jline.ConsoleRunner clojure.lang.Repl
else
  java -cp $CLOJURE_JAR clojure.lang.Script $1
fi