#!/bin/sh

# Clojure jar file
clj=~/.emacs.d/clojure/clojure.jar

# Directory where libaries/jar files can be found
clj_ext=~/.emacs.d/clojure

# Paths to add to LD_LIBRARY_PATH
# clj_lib=~/.lib

# Class execution wrapper, uncomment to use jline.
#    Make sure latest jline jar is in ~/.clojure/ before
#    uncommenting
clj_wrapper=jline.ConsoleRunner

###
# Various java options:
###

# Memory settings
# clj_opts="${clj_opts} -Xms500m -Xmx1g"
# clj_opts="${clj_opts} -XX:+UseConcMarkSweepGC"
# clj_opts="${clj_opts} -XX:+HeapDumpOnOutOfMemoryError"


# Whether to load the repl or script
if [ -z "$1" ]; then
  clj_class=clojure.lang.Repl
else
  clj_class=clojure.lang.Script
fi

clj_cp="."
[ -f /etc/clojure.conf ] && . /etc/clojure.conf
[ -f ~/.clojure.conf ]   && . ~/.clojure.conf
[ -f ~/.clojurerc ] && clj_rc=~/.clojurerc
[ -d "${clj_ext}" ] && clj_cp="${clj_cp}:${clj_ext}/*"

if [[ -n "${clj_lib}" ]]; then
    export LD_LIBRARY_PATH=${clj_lib}:$LD_LIBRARY_PATH
fi

exec java -Dpid=$$ ${clj_opts} -cp ${clj_cp}:${clj}:${clj_ext}/jline.jar ${clj_wrapper} ${clj_class} ${clj_rc} $*
